#!/bin/bash

########################################
##          Global variables          ##
########################################

progname="damp"
conf_dir="$HOME/.local/share/damp"
global_opts="phpconf httpdconf httpdvhost httpdport dbconf rootdbuser rootdbpass dbport initpath lang"
site_opts="name domain docroot database dbuser dbpass"
commands="command echo exit su who awk cat grep cp mv ls chmod sed mysql eval xdg-open read tr head rm find xargs id mkdir getopt set shift"


########################################
##        Function definitions        ##
########################################

# Define basic help text
usage () {
  echo "TODO: usage text"
}

# Error handling
error_exit () {
  echo "${progname}: ${1:-"unknown error"}" 1>&2
  exit 1
}

# Verify we have access to all necessary shell commands
check_commands () {
  if [ ! -f "${conf_dir}/setup-run" ]; then
    for i in $commands; do
      command -v $i > /dev/null 2>&1
      if [ $? -ne 0 ]; then
        error_exit "required command $i not found"
      fi
    done
    echo "${progname}: Setup has noot been run. Try ${0} setup"
  fi
}

# Executes command as the logged in user instead ot root
as_user () {
  su -c "$1" $(who am i | awk '{print $1}')
}

# Generate the default global options file for various operating systems
generate_global_conf () {
  case "$os" in
    "Red Hat"|CentOS)
      as_user "cat > \"$conf_dir/damp.conf\" <<EOF
phpconf=/etc/php.ini
httpdconf=/etc/httpd/conf/httpd.conf
httpdvhost=/etc/httpd/conf.d
httpdport=80
dbconf=/etc/my.cnf
rootdbuser=root
rootdbpass=
dbport=3306
initpath=/etc/init.d
lang=en
EOF"
      ;;
    *|Ubuntu|Debian)
      as_user "cat > \"$conf_dir/damp.conf\" <<EOF
phpconf=/etc/php5/apache2/php.ini
httpdconf=/etc/apache2/apache2.conf
httpdvhost=/etc/apache2/sites-enabled
httpdport=80
dbconf=/etc/mysql/my.cnf
rootdbuser=root
rootdbpass=
dbport=3306
initpath=/etc/init.d
lang=en
EOF"
      ;;
  esac
}

# Parse configuration file options and load into global variables
parse_conf () {
  while read propline ; do 
    # ignore comment lines
    echo "$propline" | grep "^#" >/dev/null 2>&1 && continue
    # if not empty, set the property using declare
    [ ! -z "$propline" ] && eval $propline
  done < "$1"
  if [ $? -ne 0 ]; then
    error_exit "could not parse configuration file"
  fi
}

# Detect operating system - This can probably be improved
detect_os () {
  distributions="Red CentOS Ubuntu Debian"
  os=""
  for i in $distributions; do
    cat /etc/*release | grep $i > /dev/null 2>&1
    if [ $? == 0 ]; then
      os=$i
    fi
  done
  if [ -z $os ]; then
    error_exit "unsupported operating system - perform operation manually"
  fi
  if [ $os == "Red" ]; then
    os="Red Hat"
  fi
}

# Checks if a site has been specified
requires_site () {
  if [ -z $site ]
  then
    error_exit "the requested operation requires a site"
  fi
}

# checks whether a site (really the config file) exists
site_exists () {
  [ -f "$conf_dir/sites/${1}.conf" ]
}

# Builds the FQDN for a site from the name and domain
build_fqdn () {
  if [ ! -z $domain ]
    then
      fqdn="${name}.${domain}"
    else
      fqdn="$name"
  fi
}

# Load site options into global variables
load_site () {
  site_exists "$1"
  if [ $? == 0 ]
  then
    parse_conf "$conf_dir/sites/${1}.conf"
    build_fqdn
  else
    error_exit "site does not exist"
  fi
}

# Print formatted site information
display_site () {
  echo "Site information:"
  echo "  Name:          $name"
  echo "  Domain:        $fqdn"
  echo "  Document root: $docroot"
  echo "  Database:      $database"
  echo "  DAMP config:   $conf_dir/sites/${name}.conf"
  echo "  Apache config: $httpdvhost/${name}.conf"
  echo ""
  echo "  Link:          http://${fqdn}:${httpdport}"
}

# Generate a settings.php file for a Drupal site with correct database settings
create_drupal_settings () {
  as_user "cp -f \"$docroot/sites/default/default.settings.php\" \"$docroot/sites/$fqdn/settings.php\""
  if [ $? -ne 0 ]; then
    error_exit "could not write drupal site settings file."
  fi
  grep "db_url" "$docroot/sites/$fqdn/settings.php" > /dev/null 2>&1
  if [ $? -ne 0 ]
  then
    echo "
\$databases['default']['default'] = array(
  'driver' => 'mysql',
  'database' => '$database',
  'username' => '$dbuser',
  'password' => '$dbpass',
  'host' => 'localhost',
  'collation' => 'utf8_general_ci',
);" >> "$docroot/sites/$fqdn/settings.php"
  else
    echo "
\$db_url = 'mysql://${dbuser}:${dbpass}@localhost/${database}';" >> "$docroot/sites/$fqdn/settings.php"
  fi
  chmod 644 "$docroot/sites/$fqdn/settings.php"
}

# Make sure there is no vhost file with the given name.
check_vhost () {
  if [ -f "$httpdvhost/${fqdn}.conf" ]; then
    error_exit "there is already and apache vhost with that fqdn"
  fi
}

# Generate Apache vhost configuration file for a Drupal site
create_vhost () {
  cat > "$httpdvhost/${fqdn}.conf" <<EOF
<VirtualHost *:${httpdport}>
  ServerAdmin ${USER}@localhost
  DocumentRoot ${docroot}
  ServerName ${fqdn}
  RewriteEngine On
  RewriteOptions inherit
</VirtualHost>

<Directory ${docroot}>
  Options +FollowSymLinks Indexes
  AllowOverride All
  order allow,deny
  allow from all
</Directory>
EOF
  if [ $? -ne 0 ]; then
    error_exit "could not create apache vhost file"
  fi
}

# Add or remove records from the /etc/hosts file
hosts_entry () {
  case "$1" in
    add)
      echo "127.0.0.1 $2" >> /etc/hosts
      ;;
    delete)
      hosts_line="/127.0.0.1 ${2}/d"
      sed -i "$hosts_line" /etc/hosts
      ;;
  esac
  if [ $? -ne 0 ]; then
    error_exit "could not alter hosts file"
  fi
}

# Perform MySQL database operations
manage_database () {
  case "$1" in
    create)
      mysql -u $rootdbuser --password=$rootdbpass --execute="CREATE DATABASE ${database};"
      mysql -u $rootdbuser --password=$rootdbpass --execute="GRANT ALL PRIVILEGES ON ${database}.* TO ${dbuser}@localhost IDENTIFIED BY '${dbpass}';"
      ;;
    delete)
      mysql -u $rootdbuser --password=$rootdbpass --execute="DROP USER ${dbuser}@localhost;"
      mysql -u $rootdbuser --password=$rootdbpass --execute="DROP DATABASE ${database};"
      ;;
    userdel)
      mysql -u $rootdbuser --password=$rootdbpass --execute="DROP USER ${2}@localhost;"
      ;;
    useradd)
      mysql -u $rootdbuser --password=$rootdbpass --execute="GRANT ALL PRIVILEGES ON ${database}.* TO ${2}@localhost IDENTIFIED BY '${3}';"
      ;;
  esac
  mysql -u $rootdbuser --password=$rootdbpass --execute="flush privileges;"
  if [ $? -ne 0 ]; then
    error_exit "error performing database operation"
  fi
}

# Make sure the given docroot is a valid Drupal codebase by checking the
# default.settings.php file
check_docroot () {
  if [ ! -f "${docroot}/sites/default/default.settings.php" ]; then
    error_exit "could not find default.settings.php"
  fi
}

# Make sure the site name is not already in use in this codebase
check_site_name () {
  if [ -d "${docroot}/sites/${fqdn}" ]; then
    error_exit "drupal site already exists with that fqdn"
  fi
}

# Change site options and alter files/configurations to match
alter_site () {
  # MySQL databases cannot be reliably renamed
  if [ ! -z $database ]; then
    error_exit "the database cannot be changed once a site has been created"
  fi

  # Copy user input to new variables
  for i in $site_opts; do
    if [ ! -z ${!i} ]; then
      eval new_${i}="${!i}"
    fi
  done

  # load existing site options
  load_site $site

  # Copy existing options to set of 'old' variables
  for i in $site_opts; do
    eval "old_${i}"="${!i}"
  done
  old_fqdn=$fqdn

  # Replace current site variables with user input
  for i in $site_opts; do
    new_var_name="new_${i}"
    if [ ! -z ${!new_var_name} ]; then
      eval ${i}="${!new_var_name}"
    fi
  done
  build_fqdn

  # Alter site options - move files as necessary
  check_docroot
  if [ $name != $old_name ]; then
    site_exists $name
    if [ $? -eq 0 ]; then
      error_exit "site with that name already exists"
    fi
    check_vhost
    check_site_name
    mv "${conf_dir}/sites/${old_name}.conf" "${conf_dir}/sites/${name}.conf"; [ $? -ne 0 ] && alter_error=1
  fi
  if [ $fqdn != $old_fqdn ]; then
    check_vhost
    check_site_name
    hosts_entry delete "$old_fqdn"
    hosts_entry add "$fqdn"
    mv "${old_docroot}/sites/${old_fqdn}" "${old_docroot}/sites/${fqdn}"; [ $? -ne 0 ] && alter_error=1
    mv "${httpdvhost}/${old_fqdn}.conf" "${httpdvhost}/${fqdn}.conf"; [ $? -ne 0 ] && alter_error=1
  fi
  if [ $docroot != $old_docroot ]; then
    check_site_name
    mv "${old_docroot}/sites/${fqdn}" "${docroot}/sites/${fqdn}"; [ $? -ne 0 ] && alter_error=1
  fi
  if [ $dbuser != $old_dbuser ] || [ $dbpass != $old_dbpass ]; then
    manage_database userdel "$old_dbuser"
    manage_database useradd "$dbuser" "$dbpass"
  fi
  create_vhost
  create_drupal_settings
  damp_services restart
}

# Manage Apache and MySQL services
damp_services () {
  detect_os
  service_error=0
  case "$os" in
    "Red Hat"|CentOS)
      service mysqld $1; [ $? -ne 0 ] && service_error=1
      service httpd $1; [ $? -ne 0 ] && service_error=1
      ;;
    Ubuntu)
      service mysql $1; [ $? -ne 0 ] && service_error=1
      service apache2 $1; [ $? -ne 0 ] && service_error=1
      ;;
    Debian)
      $initpath/mysql $1; [ $? -ne 0 ] && service_error=1
      $initpath/apache2 $1; [ $? -ne 0 ] && service_error=1
      ;;
  esac
  if [ $service_error -ne 0 ]; then
    error_exit "errors occurred while performing the requested operations"
  fi
}

# Print a list of site names, one per line
list_sites () {
  ls -1 "$conf_dir/sites" | sed "s/.conf//"
}

# Update Apache port settings for all sites
update_port () {
  while read line
  do
    load_site $line
    create_vhost
  done <<< "$(list_sites)"
  damp_services restart
}

# Print a site list if no site is specified, or detailed site information
site_info () {
  if [ -z $site ]
  then
    # List all sites
    site_count=$(ls -1 "$conf_dir/sites" | wc -l)
    echo "Sites installed: $site_count"
    list_sites
  else
    # Display information about a site
    load_site $site
    display_site
  fi
}

# Open a site in a web browser
open_site () {
  load_site $1
  url="http://${fqdn}:${httpdport}${2}"
  as_user "xdg-open $url > /dev/null 2>&1"
  if [ $? -ne 0 ]; then
    error_exit "could not open browser. URL is $url"
  fi
}

# Create a new site
new_site () {
  if [ -z $dbpass ]; then
    dbpass=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c8)
  fi
  for i in $site_opts; do
    if [ -z ${!i} ]
    then
      echo -n "Enter site ${i}: "
      read $i
      if [ -z ${!i} ] && [ $i != "domain" ]; then
        error_exit "$i is a required option"
      fi
    fi
    if [ $i == "name" ] && [ -z $dbuser ]; then
      dbuser="$name"
    fi
    if [ $i == "name" ] && [ -z $database ]; then
      database="$name"
    fi
  done
  site_exists $name
  if [ $? -ne 0 ]
  then
    build_fqdn
    check_docroot
    check_site_name
    check_vhost
    manage_database create
    create_vhost
    as_user "mkdir -p \"$docroot/sites/$fqdn\""
    create_drupal_settings
    chmod a+w "$docroot/sites/$fqdn"
    as_user "touch \"$conf_dir/sites/${name}.conf\""
    for i in $site_opts; do
      echo "${i}=${!i}" >> "$conf_dir/sites/${name}.conf"
      if [ $? -ne 0 ]; then
        error_exit "error writing to site configuration file"
      fi
    done
    hosts_entry add "$fqdn"
    damp_services restart
    open_site $name "/install.php"
  else
    error_exit "site with that name already exists"
  fi
}

# Remove an existing site and all associated files/configurations
remove_site () {
  load_site $site
  if [ -z $yes_to_all ]; then
    echo -n "Are you sure you want to remove site '${name}' [y|n]: "
    read sure
  else
    sure="y"
  fi
  if [ "${sure}" == "y" ] || [ "${sure}" == "Y" ]
  then
    rm -f "$conf_dir/sites/${site}.conf"
    rm -Rf "$docroot/sites/$fqdn"
    rm -f "$httpdvhost/${fqdn}.conf"
    hosts_entry delete "$fqdn"
    manage_database delete
    damp_services restart
  else
    exit 0
  fi
}

# Set site/global options
set_opts () {
  if [ -z $site ]
  then
    # Set global options
    setopts="$global_opts"
    optfile="$conf_dir/damp.conf"
    if [ ! -z $dbuser ]; then
      rootdbuser="$dbuser"
    fi
    if [ ! -z $dbpass ]; then
      rootdbpass="$dbpass"
    fi
  else
    # Set site specific options
    setopts="$site_opts"
    alter_site
    optfile="$conf_dir/sites/${name}.conf"
  fi
  for i in $setopts; do
    sed -i "s|${i}=.*|${i}=${!i}|" "$optfile"
    if [ $? -ne 0 ]; then
      error_exit "error writing to the configuration file"
    fi
    if [ $i == "httpdport" ]; then
      update_port
    fi
  done
  if [ ! -z $alter_error ]; then
    error_exit "errors occurred while altering site options"
  fi
}

get_opts () {
  if [ -z $site ]
  then
    echo "Global config file: $conf_dir/damp.conf"
    cat "$conf_dir/damp.conf"
  else
    load_site $site
    echo "$name config file: $conf_dir/sites/${name}.conf"
    cat "$conf_dir/sites/${name}.conf"
  fi
}

# Install and configure packages for the DAMP stack
setup_stack () {
  detect_os
  case "$os" in
    "Red Hat"|CentOS)
      yum install httpd mysql mysql-server php-cli php-pear php-xml php-mysql php-mbstring php-pdo php-gd php-devel
      yum groupinstall "Development Tools"
      if [ ! -z $mail ]; then
        yum install postfix
      fi
      ;;
    Ubuntu|Debian)
      apt-get install apache2 mysql-server mysql-client php5 php5-cli php5-mysql php5-xmlrpc php-pear php5-gd php5-dev build-essential
      if [ ! -z $mail ]; then
        apt-get install postfix
      fi
      a2enmod rewrite
      ;;
  esac
  if [ ! -z $mail ]; then
    apt-get install postfix
  fi
  pecl install uploadprogress
  echo "extension=uploadprogress.so" >> "$phpconf"
  echo "ServerName localhost" >> "$httpdconf"
  damp_services restart
  as_user "touch \"${conf_dir}/setup-run\""
}

# Edit service configuration files in the terminal
edit_conf () {
  if [ -z $1 ]
  then
    error_exit "no component specified"
  else
    case "$1" in
      php)
        vi $phpconf
        ;;
      httpd|apache)
        vi $httpdconf
        ;;
      db|database|mysql)
        vi $dbconf
        ;;
      *)
        error_exit "unrecognized component"
        ;;
    esac
  fi
}

# Fix permission issues for the site file system
fix_perm () {
  load_site $site
  chmod 755 "${docroot}/sites/${fqdn}" >/dev/null 2>&1
  find "${docroot}/sites/${fqdn}/files" -type d -print0 | xargs -0 chmod o+rwx >/dev/null 2>&1
  find "${docroot}/sites/${fqdn}/files" -type f -print0 | xargs -0 chmod o+rw >/dev/null 2>&1
}


########################################
##       Script execution start       ##
########################################

# Do we have all the commands we need?
check_commands

# Make sure we are running as root
if [ $(id -u) -ne 0 ]
then
  error_exit "must be run as root"
fi

# Create configuration files if not present
if [ ! -d "$conf_dir" ]; then
  as_user "mkdir -p \"$conf_dir\""
fi
if [ ! -d "$conf_dir/sites" ]; then
  as_user "mkdir -p \"$conf_dir/sites\""
fi
if [ $? -ne 0 ]; then
  error_exit "could not create configuration directories"
fi
if [ ! -f "$conf_dir/damp.conf" ]; then
  detect_os
  generate_global_conf
fi

# Parse global configuration file
parse_conf "$conf_dir/damp.conf"

# Check if we have any arguments at all
if [ -z $1 ]
then
  usage
  exit 1
fi

# Execute getopt to parse arguments
ARGS=$(getopt -o hn:d:mp:b:y -l help,name:,domain:,path:,docroot:,db:,database:,mail,phpconf:,httpdconf:,httpdvhost:,httpdport:,dbconf:,dbport:,dbuser:,dbpass:,initpath:,language: -n "$progname" -- "$@");

# Bad arguments
if [ $? -ne 0 ];
then
  exit 1
fi

# A little argument magic...
eval set -- "$ARGS";

# Process options
while true; do
  case "$1" in
    -h|--help)
      shift
      usage
      exit 0
      ;;
    -n|--name)
      shift;
      if [ -n "$1" ]; then
        name="$1"
        shift;
      fi
      ;;
    -d|--domain)
      shift;
      if [ -n "$1" ]; then
        domain="$1"
        shift;
      fi
      ;;
    -p|--path|--docroot)
      shift;
      if [ -n "$1" ]; then
        docroot="$1"
        shift;
      fi
      ;;
    -b|--db|--database)
      shift;
      if [ -n "$1" ]; then
        database="$1"
        shift;
      fi
      ;;
    -m|--mail)
      shift;
      mail="install"
      ;;
    -y)
      shift;
      yes_to_all=1
      ;;
    --phpconf)
      shift;
      if [ -n "$1" ]; then
        phpconf="$1"
        shift;
      fi
      ;;
    --httpdconf)
      shift;
      if [ -n "$1" ]; then
        httpdconf="$1"
        shift;
      fi
      ;;
    --httpdvhost)
      shift;
      if [ -n "$1" ]; then
        httpdvhost="$1"
        shift;
      fi
      ;;
    --httpdport)
      shift;
      if [ -n "$1" ]; then
        httpdport="$1"
        shift;
      fi
      ;;
    --dbconf)
      shift;
      if [ -n "$1" ]; then
        dbconf="$1"
        shift;
      fi
      ;;
    --dbport)
      shift;
      if [ -n "$1" ]; then
        dbport="$1"
        shift;
      fi
      ;;
    --dbuser)
      shift;
      if [ -n "$1" ]; then
        dbuser="$1"
        shift;
      fi
      ;;
    --dbpass)
      shift;
      if [ -n "$1" ]; then
        dbpass="$1"
        shift;
      fi
      ;;
    --initpath)
      shift;
      if [ -n "$1" ]; then
        initpath="$1"
        shift;
      fi
      ;;
    --language)
      shift;
      if [ -n "$1" ]; then
        lang="$1"
        shift;
      fi
      ;;
    --)
      shift
      break
      ;;
  esac
done

# Store operation and site parameters in global variables
operation="$1"
site="$2" 

# Process arguments and perform the requested operation
case "$operation" in
  list|info|ls)
    site_info
    ;;
  new)
    new_site
    ;;
  open)
    requires_site
    open_site $site
    ;;
  install)
    requires_site
    open_site $site "/install.php"
    ;;
  remove|delete|rm|del)
    requires_site
    remove_site
    ;;
  set|update)
    set_opts
    ;;
  get)
    get_opts
    ;;
  start|stop|restart|status)
    damp_services $operation
    ;;
  setup)
    setup_stack
    ;;
  conf|configure)
    edit_conf $site
    ;;
  fix|fixperms|fixperm)
    requires_site
    fix_perm
    ;;
  *)
    echo "${progname}: operation not recognized - try $0 --help" 1>&2
    exit 1
    ;;
esac

exit 0
